# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '演讲演示.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from code.dynamicFC import *
from code.all_npz import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 733)
        Dialog.setAutoFillBackground(True)
        Dialog.setStyleSheet("")
        self.RUN = QtWidgets.QPushButton(Dialog)
        self.RUN.setGeometry(QtCore.QRect(70, 650, 113, 32))
        self.RUN.setObjectName("RUN")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(80, 180, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 240, 113, 21))
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 300, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 240, 60, 19))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setWordWrap(False)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 300, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 60, 19))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_3.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setWordWrap(False)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 60, 19))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_4.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setWordWrap(False)
        self.label_4.setIndent(-1)
        self.label_4.setObjectName("label_4")
        self.END = QtWidgets.QPushButton(Dialog)
        self.END.setGeometry(QtCore.QRect(230, 650, 113, 32))
        self.END.setObjectName("END")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 120, 113, 21))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 360, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 360, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 160, 60, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(270, -10, 200, 130))
        self.label_7.setStyleSheet("border-image: url(:/images/logo.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 60, 19))
        self.label_9.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_9.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setWordWrap(False)
        self.label_9.setIndent(-1)
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 40, 113, 21))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(-20, 90, 481, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.NPZ = QtWidgets.QPushButton(Dialog)
        self.NPZ.setGeometry(QtCore.QRect(190, 35, 61, 32))
        self.NPZ.setObjectName("NPZ")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 291, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(220, 125, 291, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(220, 185, 291, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(220, 245, 291, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(220, 305, 291, 16))
        self.label_15.setObjectName("label_15")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(-60, 400, 491, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(220, 450, 291, 61))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(220, 570, 291, 16))
        self.label_17.setObjectName("label_17")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 430, 217, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 530, 211, 80))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.horizontalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup_2.addButton(self.radioButton_4)
        self.horizontalLayout_4.addWidget(self.radioButton_4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.RUN.raise_()
        self.comboBox.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.END.raise_()
        self.lineEdit_3.raise_()
        self.label_8.raise_()
        self.lineEdit_4.raise_()
        self.label_5.raise_()
        self.label_9.raise_()
        self.lineEdit_5.raise_()
        self.line.raise_()
        self.NPZ.raise_()
        self.label_7.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.line_2.raise_()
        self.label_16.raise_()
        self.label_17.raise_()

        self.retranslateUi(Dialog)
        self.END.clicked.connect(Dialog.close)
        self.checkBox.stateChanged.connect(self.changecb)
        self.RUN.clicked.connect(self.dynamicFC)
        self.NPZ.clicked.connect(self.txt2npz2group)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def changecb(self):
        if self.checkBox.checkState() == QtCore.Qt.Checked:
            self.groupBox.setEnabled(True)
            self.groupBox_2.setEnabled(True)
            self.label_6.setEnabled(True)

        if self.checkBox.checkState() == QtCore.Qt.Unchecked:
            self.groupBox.setEnabled(False)
            self.groupBox_2.setEnabled(False)
            self.label_6.setEnabled(False)

    def znorm(self,ts):
        import nilearn
        ts_n = []

        for i in ts:
            ts_n_a = nilearn.signal.clean(i, standardize=True)  # z-normalization time series
            ts_n.append(ts_n_a)
        ts_n = np.stack(ts_n)
        return ts_n

    def dynamicFC(self):
        import numpy as np
        import os
        from nilearn.connectome import ConnectivityMeasure
        ts_npz = np.load(self.lineEdit_3.text())

        for i in ts_npz:
            ts = ts_npz[i]
        ts = self.znorm(ts)
        ws = int(self.lineEdit.text())
        ss = int(self.lineEdit_2.text())
        wtype = self.comboBox.currentText()
        outdir = self.lineEdit_4.text()
        all_sl = sl_run(ts, ws, ss, wtype)
        if self.checkBox.checkState() == QtCore.Qt.Checked:
            if self.radioButton.isChecked():
                if self.radioButton_3.isChecked():
                    estimator = ConnectivityMeasure(kind='correlation', vectorize=True, discard_diagonal=True)
                    all_FC_sl = []
                    for sl in all_sl:
                        all_FC_sl.append(estimator.fit_transform(sl))
                if self.radioButton_4.isChecked():
                    estimator = ConnectivityMeasure(kind='correlation', vectorize=False, discard_diagonal=True)
                    all_FC_sl = []
                    for sl in all_sl:
                        all_FC_sl.append(estimator.fit_transform(sl))
            if self.radioButton_2.isChecked():
                if self.radioButton_3.isChecked():
                    estimator = ConnectivityMeasure(kind='covariance', vectorize=True, discard_diagonal=True)
                    all_FC_sl = []
                    for sl in all_sl:
                        all_FC_sl.append(estimator.fit_transform(sl))
                if self.radioButton_4.isChecked():
                    estimator = ConnectivityMeasure(kind='covariance', vectorize=False, discard_diagonal=True)
                    all_FC_sl = []
                    for sl in all_sl:
                        all_FC_sl.append(estimator.fit_transform(sl))
            all_FC_sl = np.stack(all_FC_sl)
            np.savez_compressed(os.path.join(outdir, 'dfc_ts_output.npz'), all_sl=all_sl)
            np.savez_compressed(os.path.join(outdir, 'dfc_dfc_output.npz'), all_FC_sl=all_FC_sl)

        if self.checkBox.checkState() == QtCore.Qt.Unchecked:
            np.savez_compressed(os.path.join(outdir, 'dfc_ts_output.npz'), all_sl=all_sl)

    def txt2npz2group(self):
        dir = self.lineEdit_5.text()
        txt2npz(dir)
        allts(dir)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Computing Dynamic Functional Connectivity Tool"))
        self.RUN.setText(_translate("Dialog", "RUN"))
        self.comboBox.setCurrentText(_translate("Dialog", "hamming"))
        self.comboBox.setItemText(0, _translate("Dialog", "hamming"))
        self.comboBox.setItemText(1, _translate("Dialog", "hanning"))
        self.comboBox.setItemText(2, _translate("Dialog", "tukey"))
        self.comboBox.setItemText(3, _translate("Dialog", "gaussian"))
        self.comboBox.setItemText(4, _translate("Dialog", "rect"))
        self.label.setText(_translate("Dialog", "ws:"))
        self.label_2.setText(_translate("Dialog", "ss:"))
        self.label_3.setText(_translate("Dialog", "wtype:"))
        self.label_4.setText(_translate("Dialog", "ts:"))
        self.END.setText(_translate("Dialog", "END"))
        self.label_8.setText(_translate("Dialog", "output:"))
        self.label_9.setText(_translate("Dialog", "ts:"))
        self.NPZ.setText(_translate("Dialog", "npz"))
        self.label_10.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* full path of a folder which contains all <span style=\" font-weight:600;\">ts.txt</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">* full path of the </span><span style=\" font-weight:600; font-style:italic;\">all_ts.npz</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">* window shape</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">* window size</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:italic;\"><br /></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">* step size</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">* computing fc between </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">   adjacent windows</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">* lower triangular or not?</span></p></body></html>"))
        self.checkBox.setText(_translate("Dialog", "ConnectivityMeasures"))
        self.radioButton.setText(_translate("Dialog", "Correlation"))
        self.radioButton_2.setText(_translate("Dialog", "Covariance"))
        self.label_6.setText(_translate("Dialog", "Vectorize:"))
        self.radioButton_3.setText(_translate("Dialog", "True"))
        self.radioButton_4.setText(_translate("Dialog", "False"))
import code.resources_rc
